import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Designo App | Marko Nikolajević',
  description: 'Generated by create next app'
};

const jost = Jost({ subsets: ['latin'] });

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={jost.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
